version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-rinha-go
    environment:
      POSTGRES_DB: rinha-2025-go
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
